version: "3.8"
services:
  redis:
    image: redis:7.0.6
    container_name: dev_redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}

  postgres:
    image: postgres:14
    container_name: dev_db
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  redis:
    name: dev
  postgres:
    name: dev
